name = "Warriors Haven Framework"
author = "thegamecracks"
prefix = "whf"
mainprefix = "z"

[version]
major = 2026
minor = 1
patch = 1

[files]
include = [
    "logo.jpg",
    "README.md",
]

[hemtt.build]
pdrive = "disallow"

[hemtt.check]
pdrive = "ignore"

[lints.sqf]
if_assign = false
reasign_reserved_variable = false
